import { policyLayer } from "@zintus-continuity/policy";

export {
  type AuthenticationDenialReason,
  type AuthenticationDenied,
  type AuthenticationResult,
  type AuthenticationService,
  type AuthenticationVerified,
  authenticationLimits,
  createAuthenticationService,
  type IdentityAuthorityDenialReason,
  type IdentityAuthorityDenied,
  type IdentityAuthorityLookup,
  type MembershipResolved,
  type MembershipResult,
  membershipRoleAllowlist,
  type ServiceIdentityResult,
  type ServiceIdentityVerified,
} from "./authentication.js";
export {
  createOutboxConsumeService,
  createOutboxDeadLetterService,
  createOutboxPublishService,
  type InboxReceipt,
  type InboxReceiptCommand,
  type InboxReceiptResult,
  type OutboxAcknowledgeInput,
  type OutboxAcknowledgeResult,
  type OutboxAppendResult,
  type OutboxClaimResponse,
  type OutboxClaimResult,
  type OutboxConsumeService,
  type OutboxDeadLetter,
  type OutboxDeadLetterService,
  type OutboxDelivery,
  type OutboxMessage,
  type OutboxMessageCreateCommand,
  type OutboxPublishService,
  type OutboxRepository,
  type OutboxScope,
} from "./c07-outbox-inbox.js";
export {
  createDatabaseTenantIsolationService,
  type DatabaseEventProjection,
  type DatabaseEventResult,
  type DatabaseEventRow,
  type DatabasePayloadAnchorResult,
  type DatabasePayloadAnchorRow,
  type DatabaseTenantIsolationReader,
  type DatabaseTenantIsolationService,
} from "./database-tenant-isolation.js";
export {
  createEventRevisionRequestService,
  type EventRevisionRequest,
  type EventRevisionRequestCommand,
  type EventRevisionRequestPayload,
  type EventRevisionRequestRepository,
  type EventRevisionRequestResult,
  type EventRevisionRequestService,
} from "./event-ledger.js";
export {
  createRecallLedgerService,
  type DisclosedRecall,
  type DisclosureReceipt,
  isIssuedMemoryAskResult,
  type MemoryAccessTier,
  type MemoryAskCommand,
  type MemoryAskResult,
  type MemoryCorrectionCommand,
  type MemoryCorrectionDisposition,
  type MemoryCorrectionReplacement,
  type MemoryCorrectionResult,
  type MemoryFact,
  type MemoryFactStatus,
  type MemoryOperation,
  type MemoryPropagationEntry,
  type MemoryScope,
  type MemorySensitivity,
  type MemoryTeachCommand,
  type MemoryTeachResult,
  type RecallLedgerRepository,
  type RecallLedgerService,
  type RecallResult,
  type ReceiptRecalledEntry,
  type ReceiptWithheldEntry,
  recallEmbeddingDimension,
  recallEmbeddingSpace,
  recallPolicyVersion,
  type WithheldReason,
} from "./h1-recall-ledger.js";
export {
  type EmbeddingPadResult,
  type PersistentEmbeddingSpace,
  padLocalEmbeddingToPersistent,
  persistentBedrockEmbeddingSpace,
  persistentEmbeddingDimension,
  persistentSyntheticEmbeddingSpace,
  unwrapPersistentSyntheticEmbedding,
} from "./h2-embedding-space.js";
export {
  answerFromMemoryAsk,
  type BedrockDenialCode,
  type BedrockDenied,
  type BedrockEmbeddingSucceeded,
  type BedrockEmbedPort,
  type BedrockGeneratePort,
  type BedrockGenerationSucceeded,
  type BedrockUnknown,
  type BedrockUsage,
  createFailClosedBedrockPorts,
  type DemoAnswer,
  type DemoAnswerResult,
} from "./h3-demo-agent.js";
export {
  compileHackathonContext,
  createHackathonLive,
  type HackathonLiveDependencies,
  type HackathonLiveFailure,
  type HackathonLiveProvider,
  type HackathonLiveResult,
  type HackathonLiveStep,
  type HackathonLiveStore,
  type HackathonLiveSuccess,
  type HackathonRetrievalPolicy,
  type HackathonRetrievalPolicyRequest,
  hackathonLiveProfile,
} from "./hackathon-live.js";
export {
  type FaultJournalEntry,
  type FaultRule,
  type LocalFixtureIdentityDefinition,
  type LocalHarnessErrorCode,
  type LocalIdentity,
  type LocalJson,
  type LocalJsonArray,
  type LocalJsonObject,
  type LocalProviderFixture,
  type LocalProviderInvocation,
  type LocalScope,
  type LocalStateRead,
  type LocalStateResult,
  type LocalStateWrite,
  type LocalSyntheticController,
  type LocalSyntheticFixture,
  type LocalSyntheticFixtureDefinition,
  type LocalSyntheticRuntime,
  localHarnessBounds,
  localSyntheticFixture,
  type ManualClockPort,
  type ProviderResult,
  type QueueDelivery,
  type QueueEnqueueMessage,
  type QueueEnqueueResult,
  type QueueMessage,
  type QueueResult,
  type VectorMatch,
} from "./local-harness-ports.js";
export {
  createTenantAuthorityBinder,
  createTenantContextService,
  type TenantAuthorityBinder,
  type TenantAuthoritySource,
  type TenantContextDenialReason,
  type TenantContextDenied,
  type TenantContextIdIssuer,
  type TenantContextIssued,
  type TenantContextResult,
  type TenantContextService,
  tenantContextLimits,
} from "./tenant-context.js";

export const applicationLayer = {
  name: "application" as const,
  policy: policyLayer.name,
};
